sudo: required
services:
  - docker

before_install:
  - docker-compose -f cicd/docker-compose-build.yml build

script:
  - docker-compose -f cicd/docker-compose-build.yml up

after_script:
  - docker-compose -f cicd/docker-compose-build.yml down
  - docker rm -f $(docker ps -aq)
